version = "3.8.3"
runner.dialect = scala3

maxColumn = 120
trailingCommas = never

indent.main = 2
indent.extendSite = 2
indent.withSiteRelativeToExtends = 0
indent.defnSite = 2

newlines.implicitParamListModifierPrefer = after

align.arrowEnumeratorGenerator = true
align.openParenDefnSite = false

docstrings.style = Asterisk
docstrings.blankFirstLine = yes

rewrite.scala3.convertToNewSyntax = yes
rewrite.scala3.removeOptionalBraces = no
rewrite.scala3.insertEndMarkerMinLines = 15

rewrite.rules = [
  RedundantBraces,
  RedundantParens,
  SortModifiers,
  Imports
]

rewrite.imports.sort = ascii
rewrite.imports.groups = [
  ["java\\..*"],
  ["scala\\..*"],
  ["zio\\..*"],
  ["(?!com\\.chriskimberley.*).*"],
  ["com\\.chriskimberley.*"]
]
